language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - docker build -t udagram-reverse-proxy .
  # - docker tag simple-reverse-proxy DOCKER_HUB_ACCOUNT/simple-reverse-proxy:latest
  - docker tag udagram-reverse-proxy arunchacko/ud-repo-jun1:udagram-reverse-proxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push DOCKER_HUB_ACCOUNT/simple-reverse-proxy
  - docker push arunchacko/ud-repo-jun1:udagram-reverse-proxy

